/**
 * Icon barrel — Lucide components aliased to legacy TailAdmin export names so
 * existing imports keep working. Country flags stay as custom SVGs (SVGR).
 */
export {
  TriangleAlert as AlertIcon,
  ArrowDown as ArrowDownIcon,
  ArrowRight as ArrowRightIcon,
  ArrowUp as ArrowUpIcon,
  AudioLines as AudioIcon,
  Bookmark as BookmarkIcon,
  Bolt as BoltIcon,
  Box as BoxIcon,
  Box as BoxTapped,
  Boxes as BoxCubeIcon,
  Package as BoxIconLine,
  Calendar as CalenderIcon,
  MessageCircle as ChatIcon,
  Check as CheckLineIcon,
  CircleCheck as CheckCircleIcon,
  ChevronDown as AngleDownIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as AngleUpIcon,
  ChevronUp as ChevronUpIcon,
  X as CloseIcon,
  X as CloseLineIcon,
  Copy as CopyIcon,
  FileText as DocsIcon,
  CircleDollarSign as DollarLineIcon,
  Download as DownloadIcon,
  Mail as EnvelopeIcon,
  Eye as EyeIcon,
  EyeOff as EyeCloseIcon,
  File as FileIcon,
  Folder as FolderIcon,
  LayoutGrid as GridIcon,
  Users as GroupIcon,
  Ellipsis as HorizontaLDots,
  OctagonAlert as ErrorIcon,
  Info as InfoIcon,
  List as ListIcon,
  Lock as LockIcon,
  Mail as MailIcon,
  Ellipsis as MoreDotIcon,
  FileText as PageIcon,
  Send as PaperPlaneIcon,
  Pencil as PencilIcon,
  PieChart as PieChartIcon,
  Plug as PlugInIcon,
  Plus as PlusIcon,
  Sparkles as ShootingStarIcon,
  Table as TableIcon,
  ClipboardList as TaskIcon,
  Clock as TimeIcon,
  Trash2 as TrashBinIcon,
  Upload as UploadIcon,
  CircleUser as UserCircleIcon,
  User as UserIcon,
  Video as VideoIcon,
} from "lucide-react";

export { default as DeFlagIcon } from "./flag-de.svg";
export { default as EsFlagIcon } from "./flag-es.svg";
export { default as SaFlagIcon } from "./flag-sa.svg";
export { default as UsFlagIcon } from "./flag-us.svg";
